=== api-evangelist/hugging-face/json-schema/hugging-face-hub-dataset-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "DatasetSummary",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "description": "Dataset repository ID"
    },
    "author": {
      "type": "string"
    },
    "sha": {
      "type": "string"
    },
    "lastModified": {
      "type": "string"
    },
    "private": {
      "type": "boolean"
    },
    "gated": {
      "type": "boolean"
    },
    "disabled": {
      "type": "boolean"
    },
    "tags": {
      "type": "array"
    },
    "downloads": {
      "type": "integer"
    },
    "likes": {
      "type": "integer"
    },
    "createdAt": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  }
}

=== api-evangelist/hugging-face/examples/hugging-face-hub-dataset-summary-example.json
{
  "_id": "500123",
  "id": "abc123",
  "author": "example_value",
  "sha": "example_value",
  "lastModified": "example_value",
  "private": true,
  "gated": true,
  "disabled": true,
  "tags": [],
  "downloads": 10,
  "likes": 10,
  "createdAt": "example_value",
  "description": "A sample description."
}
